// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVQ7TjYYGxe8k7Fo1P0eC34mHrh75v31A',
    appId: '1:649777092181:web:dc47c78e1d95055c631b70',
    messagingSenderId: '649777092181',
    projectId: 'ar-proj-d08db',
    authDomain: 'ar-proj-d08db.firebaseapp.com',
    storageBucket: 'ar-proj-d08db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVQ7TjYYGxe8k7Fo1P0eC34mHrh75v31A',
    appId: '1:649777092181:android:b8c8d62f7e006e3f631b70',
    messagingSenderId: '649777092181',
    projectId: 'ar-proj-d08db',
    storageBucket: 'ar-proj-d08db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVQ7TjYYGxe8k7Fo1P0eC34mHrh75v31A',
    appId: '1:649777092181:ios:a5bb4f3c99cff4ba631b70',
    messagingSenderId: '649777092181',
    projectId: 'ar-proj-d08db',
    storageBucket: 'ar-proj-d08db.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVQ7TjYYGxe8k7Fo1P0eC34mHrh75v31A',
    appId: '1:649777092181:ios:a5bb4f3c99cff4ba631b70',
    messagingSenderId: '649777092181',
    projectId: 'ar-proj-d08db',
    storageBucket: 'ar-proj-d08db.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );
}
